#pragma once
#include <gtkmm.h>
#include <gdk/gdk.h>

namespace SceneReconstruction {
  /** @class SceneTab "scenetab.h"
   * Base tab class that needs to be extended
   * @author Bastian Klingen
   */
  class SceneTab {
    public:
      /** Constructor
       * @param text Text for the label of the tab
       */
      SceneTab(Glib::ustring);
      /** Destructor */
      virtual ~SceneTab();

    private:
      Gtk::Label*  label;

    public:
      /** Getter for the label of the tab of this class
       * @return Gtk::Label the label of the tab of this class
       */
	    Gtk::Label&  get_label();
      /** Getter for the tab of this class
       * @return Gtk::Widget the tab generated by this class
       */
      virtual Gtk::Widget& get_tab();
  };
}

